---
- name: Copy sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: "644"
  register: _sysctl

- name: sysctl -p
  command: /usr/sbin/sysctl -p
  ignore_errors: True
  when:
    - _sysctl is changed

- name: Apply sysctl settings
  sysctl:
    name: "{{ item.key }}"
    reload: yes
    state: "{{ item.state | default('present') }}"
    sysctl_set: "{{ item.sysctl_set | default(omit) }}"
    ignoreerrors: "{{ item.ignoreerrors | default(omit) }}"
    sysctl_file: "{{ item.sysctl_file | default('/etc/sysctl.d/user.conf') }}"
    value: "{{ item.value }}"
  loop: "{{ sysctl_items }}"
  ignore_errors: True
  when:
    - sysctl_items|length > 0
    - ansible_virtualization_type != "docker"
